#!/usr/bin/env python3

import os

core_path_ext = os.path.join(os.path.dirname(os.path.abspath(__file__)) , 'cate_src')

import sys, csv, itertools, math, platform, random, warnings, timeit
import numpy as np
from scipy.interpolate import interp1d
from scipy import optimize
import matplotlib.pyplot as plt
import matplotlib.patches as patches
from matplotlib.collections import PatchCollection
import matplotlib.colors as colors
from matplotlib.pyplot import Figure
import matplotlib.patheffects as pe
from matplotlib.backends.backend_qt5agg import FigureCanvasQTAgg as FigureCanvas
from matplotlib.backends.backend_qt5agg import NavigationToolbar2QT as NavigationToolbar
from PyQt5 import QtGui, QtCore
from PyQt5.QtWidgets import *

#Importing external functions

sys.path.append(core_path_ext)

from cond_models.melt_odd import * #Conductivity functions of melts
from cond_models.fluids_odd import * #Conductivity functions of fluids

warnings.filterwarnings("ignore", category=RuntimeWarning) #ignoring many RuntimeWarning printouts that are utterly useless

#Color coding class for fancy-colored print-outs.
class bcolors:
	BLUE = '\033[94m'
	GREEN = '\033[92m'
	RED = '\033[91m'
	B = '\033[0m'
	NC ='\x1b[0m'
	

#Version 0.1, June. 2023.
#CATE - (C)antle (A)nalysis (T)ools for (E)lectromagnetics
#Program written by Sinan Ozaydin (Macquarie University, School of Natural Sciences
#sciences, Australia).

#Indentation method: hard tabs ('\t')

#Works with Python3
#Required libraries: numpy,scipy,matplotlib,PyQt5

#Installation of libraries:
#In Linux (mac included) distros through terminal:
#pip install numpy,scipy,matplotlib,PyQt5
#In Windows skip sudo.

print(bcolors.GREEN + '#############################################')
print(' ')
print(' ')
print(' ')
print(bcolors.GREEN + '                  CATE 0.1')
print(' ')
print(bcolors.BLUE + '            Crust Analysis Tools')
print('                     for')
print('               Electromagnetics')
print(' ')
print(' ')
print(' ')
print(bcolors.GREEN + '#############################################')
print(bcolors.BLUE + 'developed by Sinan Ozaydin,' + bcolors.RED +  ' School of Geosciences, University of Sydney')
print(' ')
print(' ')
print(bcolors.NC + 'for questions, email: sinan.ozaydin@protonmail.com or sinan.ozaydin@sydney.edu.au')
print('Initializing the software...')

class CATE(QMainWindow):

	def __init__(self, core_path = core_path_ext, parent = None):

		super(CATE,self).__init__(parent)

		self.core_path = core_path
		self.working_path = os.getcwd()

		if platform.system() == 'Windows':
			self.commandmv = 'move'
		else:
			self.commandmv = 'mv'

		args_input = sys.argv
		if len(args_input) == 1:
			CATE.arguments_load = False
			CATE.composition_args_path = False
		else:
			CATE.arguments_load = True
			try:
				CATE.composition_args_path = args_input[1]
			except IndexError:
				pass

		self.setMinimumSize(1800,1000)
		self.setStyleSheet("QMainWindow{background-color: #ebfaeb;border: 1px solid black}")
		self.setWindowTitle("CATE")
		
		#Defining Menubar items
		mainMenu = self.menuBar()
		mainMenu.setNativeMenuBar(False)
		mainMenu.setStyleSheet("QMenuBar{background-color: #ccffcc;border: 1px solid black}")
		fileMenu = mainMenu.addMenu('Main')
		mainMenu.setStyleSheet("QMenuBar{background-color: #ccffcc;border: 1px solid black}")
		
		#ENV FILE BUTTON
		infoMain = QAction("&Info", self)
		infoMain.setShortcut("Ctrl+O")
		infoMain.triggered.connect(self.info_main)
		fileMenu.addAction(infoMain)

		self.home()
		
	def home(self):
		
		#Setting up initial variables.

		self.data_existence = False
		self.composition_readfile = False
		CATE.loaded_file = False

		CATE.plot_style_list = ['ggplot', 'default', 'classic','bmh', 'fast', 'seaborn', 'seaborn-colorblind',
		'seaborn-deep','seaborn-pastel', 'seaborn-dark','fivethirtyeight','grayscale']
		CATE.plot_style_selection = 0

		CATE.model_method_grt = 0

		CATE.grt_cond_selection = 0
		CATE.fluid_cond_selection = 0
		CATE.melt_cond_selection = 0
		CATE.sulfide_cond_selection = 0
		CATE.graphite_cond_selection = 0

		CATE.granite_cond_selection = 0
		CATE.granulite_cond_selection = 0
		CATE.sandstone_cond_selection = 0
		CATE.gneiss_cond_selection = 0
		CATE.amphibolite_cond_selection = 0

		self.rock_cond_selections = [CATE.granite_cond_selection, CATE.granulite_cond_selection, CATE.sandstone_cond_selection, CATE.gneiss_cond_selection,
				   CATE.amphibolite_cond_selection]
		
		CATE.quartz_cond_selection = 0
		CATE.plag_cond_selection = 0
		CATE.amp_cond_selection = 0
		CATE.kfelds_cond_selection = 0
		CATE.pyx_cond_selection = 0
		CATE.mica_cond_selection = 0
		CATE.clay_cond_selection = 0

		self.minerals_cond_selections = [CATE.quartz_cond_selection, CATE.plag_cond_selection, CATE.amp_cond_selection, CATE.kfelds_cond_selection, CATE.pyx_cond_selection,
				   CATE.mica_cond_selection, CATE.clay_cond_selection]

		CATE.fluid_or_melt_method = 0
		CATE.solid_phase_method = 0
		
		self.granite_frac = np.zeros(1)
		self.granulite_frac = np.zeros(1)
		self.sandstone_frac = np.zeros(1)
		self.gneiss_frac = np.zeros(1)
		self.amphibolite_frac = np.zeros(1)
		
		self.quartz_frac = np.zeros(1)
		self.plag_frac = np.zeros(1)
		self.amp_frac = np.zeros(1)
		self.kfelds_frac = np.zeros(1)
		self.pyx_frac = np.zeros(1)
		self.mica_frac = np.zeros(1)
		self.clay_frac = np.zeros(1)
		
		self.melt_fluid_frac = np.zeros(1)
		
		CATE.phs_mix_method = 0
		CATE.phs_melt_mix_method = 0
		
		CATE.melt_fluid_m = 5
		
		CATE.granite_m = 4
		CATE.granulite_m = 4
		CATE.sandstone_m = 4
		CATE.gneiss_m = 4
		CATE.amphibolite_m = 4
		
		CATE.quartz_m = 1
		CATE.plag_m = 2.5
		CATE.amp_m = 4
		CATE.kfelds_m = 2.5
		CATE.pyx_m = 4
		CATE.mica_m = 4
		CATE.clay_m = 4

		#Setting up the blank canvas on the main page.

		self.canvas_widget = QFrame(self)
		self.canvas_widget.setGeometry(500,50,1250,925)
		self.canvas_widget.setStyleSheet("border:1.25px solid #768795")
		self.canvaslayout = QVBoxLayout(self.canvas_widget)

		#Using the internal matplotlib style ggplot
		plt.style.use('ggplot')
		self.fig = Figure()
		self.fig.patch.set_facecolor('#EFF0F1')

		self.canvas = FigureCanvas(self.fig)
		self.toolbar = NavigationToolbar(self.canvas, self)
		self.toolbar.setStyleSheet("QToolBar { border: 0px ; : #889DAE}")
		self.canvaslayout.addWidget(self.toolbar)
		self.canvaslayout.addWidget(self.canvas)

		#Reading parameter files...

		self.read_cond_models()

		#Defining buttons on the MainWindow
		properties_mark = QLabel(self)
		properties_mark.setText('Setup')
		properties_mark.setStyleSheet("QLabel {font:bold};fontsize: 10pt;color: red")
		properties_mark.move(65,35)

		#conductivity button

		cond_btn = QPushButton('Conducitivity Models', self)
		cond_btn.move(10,65)
		cond_btn.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		cond_btn.clicked.connect(self.info_main)
		self.cond_pop = None

		mix_btn = QPushButton('Phase Mixing', self)
		mix_btn.move(10,100)
		mix_btn.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		mix_btn.clicked.connect(self.phase_mixing_popup)
		self.phs_mix_popup = None
		
		int_btn = QPushButton('Phase Interconnectivity', self)
		int_btn.move(10,135)
		int_btn.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		int_btn.clicked.connect(self.phase_intercon_popup)
		self.phs_intercon_popup = None

		#radiobutton melt or fluid

		fluid_phases_mark = QLabel(self)
		fluid_phases_mark.setText('Fluid Phases')
		fluid_phases_mark.setStyleSheet("QLabel {font:bold};fontsize: 10pt;color: red")
		fluid_phases_mark.move(290,35)

		btn_fluid_phase_setup = QPushButton("Fluid Phase Setup", self)
		btn_fluid_phase_setup.clicked.connect(self.fluid_phase_popup)
		btn_fluid_phase_setup.setStyleSheet("QPushButton {min-width: 18em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		btn_fluid_phase_setup.move(200,65)
		self.fluid_melt_pop = None

		btn_melt_content= QPushButton("Fluid-Melt Content (%)", self)
		btn_melt_content.clicked.connect(self.get_fluid_melt_content)
		btn_melt_content.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.melt_content_textbox = QLineEdit(str(0.0), self)
		self.melt_content_textbox.setEnabled(False)
		self.melt_content_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		btn_melt_content.move(200,100)
		self.melt_content_textbox.move(370,100)

		CATE.btn_salinity_fluid= QPushButton("Fluid Salinity (%wt)", self)
		CATE.btn_salinity_fluid.clicked.connect(self.get_salinity)
		if CATE.fluid_or_melt_method == 0:
			CATE.btn_salinity_fluid.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.fluid_or_melt_method == 1:
			CATE.btn_salinity_fluid.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		CATE.btn_salinity_fluid.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.salinity_textbox = QLineEdit(str(0.0), self)
		self.salinity_textbox.setEnabled(False)
		self.salinity_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_salinity_fluid.move(200,135)
		self.salinity_textbox.move(370,135)

		CATE.btn_co2_melt = QPushButton("Melt CO2 (ppm)", self)
		CATE.btn_co2_melt.clicked.connect(self.get_co2_melt)
		if CATE.fluid_or_melt_method == 1:
			CATE.btn_co2_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.fluid_or_melt_method == 0:
			CATE.btn_co2_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.co2_melt_textbox = QLineEdit(str(0.0), self)
		self.co2_melt_textbox.setEnabled(False)
		self.co2_melt_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_co2_melt.move(200,170)
		self.co2_melt_textbox.move(370,170)

		CATE.btn_h2o_melt = QPushButton("Melt H2O (ppm)", self)
		CATE.btn_h2o_melt.clicked.connect(self.get_h2o_melt)
		if CATE.fluid_or_melt_method == 1:
			CATE.btn_h2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.fluid_or_melt_method == 0:
			CATE.btn_h2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.h2o_melt_textbox = QLineEdit(str(0.0), self)
		self.h2o_melt_textbox.setEnabled(False)
		self.h2o_melt_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_h2o_melt.move(200,205)
		self.h2o_melt_textbox.move(370,205)
		
		CATE.btn_nao_melt = QPushButton("Melt NaO (%wt)", self)
		CATE.btn_nao_melt.clicked.connect(self.get_nao_melt)
		if CATE.fluid_or_melt_method == 1:
			CATE.btn_nao_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.fluid_or_melt_method == 0:
			CATE.btn_nao_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.nao_melt_textbox = QLineEdit(str(0.0), self)
		self.nao_melt_textbox.setEnabled(False)
		self.nao_melt_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_nao_melt.move(200,235)
		self.nao_melt_textbox.move(370,235)

		CATE.btn_k2o_melt = QPushButton("Melt K2O (%wt)", self)
		CATE.btn_k2o_melt.clicked.connect(self.get_k2o_melt)
		if CATE.fluid_or_melt_method == 1:
			CATE.btn_k2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.fluid_or_melt_method == 0:
			CATE.btn_k2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.k2o_melt_textbox = QLineEdit(str(0.0), self)
		self.k2o_melt_textbox.setEnabled(False)
		self.k2o_melt_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_k2o_melt.move(200,270)
		self.k2o_melt_textbox.move(370,270)
		
		solid_phases_mark = QLabel(self)
		solid_phases_mark.setText('Solid Phases')
		solid_phases_mark.setStyleSheet("QLabel {font:bold}; min-width: 12em ; fontsize: 10pt;color: red")
		solid_phases_mark.move(200,400)

		btn_solid_phase_setup = QPushButton("Solid Phase Setup", self)
		btn_solid_phase_setup.clicked.connect(self.solid_phase_popup)
		btn_solid_phase_setup.setStyleSheet("QPushButton {min-width: 18em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		btn_solid_phase_setup.move(110,435)
		self.solid_phase_pop = None

		CATE.btn_bckgr_res = QPushButton("Backgr. Resistivity", self)
		CATE.btn_bckgr_res.clicked.connect(self.get_bckgr_res)
		if CATE.solid_phase_method == 0:
			CATE.btn_bckgr_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.solid_phase_method == 1:
			CATE.btn_bckgr_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_bckgr_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.bckgr_res_textbox = QLineEdit(str(0.0), self)
		self.bckgr_res_textbox.setEnabled(False)
		self.bckgr_res_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_bckgr_res.move(10,470)
		self.bckgr_res_textbox.move(140,470)

		line_mark = QLabel(self)
		line_mark.setText('------------------------------------------')
		line_mark.setStyleSheet("QLabel {font:bold}; min-width: 100em ; fontsize: 10pt;color: red")
		line_mark.move(20,505)

		CATE.btn_granite_res = QPushButton("Granite", self)
		CATE.btn_granite_res.clicked.connect(lambda: self.get_rock_value(textbox_obj=self.granite_frac_textbox, param = "granite_frac", rock = "Granite"))
		if CATE.solid_phase_method == 1:
			CATE.btn_granite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_granite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_granite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.granite_frac_textbox = QLineEdit(str(0.0), self)
		self.granite_frac_textbox.setEnabled(False)
		self.granite_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_granite_res.move(10,540)
		self.granite_frac_textbox.move(140,540)

		CATE.btn_granulite_res = QPushButton("Granulite", self)
		CATE.btn_granulite_res.clicked.connect(lambda: self.get_rock_value(textbox_obj=self.granulite_frac_textbox, param = "granulite_frac", rock = "Granulite"))
		if CATE.solid_phase_method == 1:
			CATE.btn_granulite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_granulite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_granulite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.granulite_frac_textbox = QLineEdit(str(0.0), self)
		self.granulite_frac_textbox.setEnabled(False)
		self.granulite_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_granulite_res.move(10,575)
		self.granulite_frac_textbox.move(140,575)

		CATE.btn_sandstone_res = QPushButton("Sandstone", self)
		CATE.btn_sandstone_res.clicked.connect(lambda: self.get_rock_value(textbox_obj=self.sandstone_frac_textbox, param = "sandstone_frac", rock = "Sandstone"))
		if CATE.solid_phase_method == 1:
			CATE.btn_sandstone_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_sandstone_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_sandstone_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.sandstone_frac_textbox = QLineEdit(str(0.0), self)
		self.sandstone_frac_textbox.setEnabled(False)
		self.sandstone_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_sandstone_res.move(10,610)
		self.sandstone_frac_textbox.move(140,610)

		CATE.btn_gneiss_res = QPushButton("Gneiss", self)
		CATE.btn_gneiss_res.clicked.connect(lambda: self.get_rock_value(textbox_obj=self.gneiss_frac_textbox, param = "gneiss_frac", rock = "Gneiss"))
		if CATE.solid_phase_method == 1:
			CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.gneiss_frac_textbox = QLineEdit(str(0.0), self)
		self.gneiss_frac_textbox.setEnabled(False)
		self.gneiss_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_gneiss_res.move(250,540)
		self.gneiss_frac_textbox.move(380,540)

		CATE.btn_amphibolite_res = QPushButton("Amphibolite", self)
		CATE.btn_amphibolite_res.clicked.connect(lambda: self.get_rock_value(textbox_obj=self.amphibolite_frac_textbox, param = "amphibolite_frac", rock = "Amphibolite"))
		if CATE.solid_phase_method == 1:
			CATE.btn_amphibolite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_amphibolite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		self.amphibolite_frac_textbox = QLineEdit(str(0.0), self)
		self.amphibolite_frac_textbox.setEnabled(False)
		self.amphibolite_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_amphibolite_res.move(250,575)
		self.amphibolite_frac_textbox.move(380,575)
		
		total_label_1 = QLabel(self)
		total_label_1.setText('Total:')
		total_label_1.setStyleSheet("QLabel {font:bold}; min-width: 100em ; fontsize: 10pt;color: red")
		total_label_1.move(250,610)
		
		self.total_rock_textbox = QLineEdit(str(0.0), self)
		self.total_rock_textbox.setEnabled(False)
		self.total_rock_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		self.total_rock_textbox.move(380,610)


		line_mark_2 = QLabel(self)
		line_mark_2.setText('------------------------------------------')
		line_mark_2.setStyleSheet("QLabel {font:bold}; min-width: 100em ; fontsize: 10pt;color: red")
		line_mark_2.move(20,645)

		CATE.btn_quartz_res = QPushButton("Quartz", self)
		CATE.btn_quartz_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.quartz_frac_textbox, param = "quartz_frac", mineral = "Quartz"))
		if CATE.solid_phase_method == 1:
			CATE.btn_quartz_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_quartz_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_quartz_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.quartz_frac_textbox = QLineEdit(str(0.0), self)
		self.quartz_frac_textbox.setEnabled(False)
		self.quartz_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_quartz_res.move(10,680)
		self.quartz_frac_textbox.move(140,680)

		CATE.btn_plag_res = QPushButton("Plagioclase", self)
		CATE.btn_plag_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.plag_frac_textbox, param = "plag_frac", mineral = "Plagioclase"))
		if CATE.solid_phase_method == 1:
			CATE.btn_plag_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_plag_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_plag_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.plag_frac_textbox = QLineEdit(str(0.0), self)
		self.plag_frac_textbox.setEnabled(False)
		self.plag_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_plag_res.move(10,715)
		self.plag_frac_textbox.move(140,715)

		CATE.btn_amp_res = QPushButton("Amphibole", self)
		CATE.btn_amp_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.amp_frac_textbox, param = "amp_frac", mineral = "Amphibole"))
		if CATE.solid_phase_method == 1:
			CATE.btn_amp_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_amp_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_amp_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.amp_frac_textbox = QLineEdit(str(0.0), self)
		self.amp_frac_textbox.setEnabled(False)
		self.amp_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_amp_res.move(10,750)
		self.amp_frac_textbox.move(140,750)
		
		CATE.btn_kfelds_res = QPushButton("K-Feldspar", self)
		CATE.btn_kfelds_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.kfelds_frac_textbox, param = "kfelds_frac", mineral = "K-Feldspar"))
		if CATE.solid_phase_method == 1:
			CATE.btn_kfelds_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_kfelds_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_kfelds_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.kfelds_frac_textbox = QLineEdit(str(0.0), self)
		self.kfelds_frac_textbox.setEnabled(False)
		self.kfelds_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_kfelds_res.move(10,785)
		self.kfelds_frac_textbox.move(140,785)
		
		CATE.btn_pyx_res = QPushButton("Pyroxenes", self)
		CATE.btn_pyx_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.pyx_frac_textbox, param = "pyx_frac", mineral = "Pyroxene"))
		if CATE.solid_phase_method == 1:
			CATE.btn_pyx_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_pyx_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_pyx_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.pyx_frac_textbox = QLineEdit(str(0.0), self)
		self.pyx_frac_textbox.setEnabled(False)
		self.pyx_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_pyx_res.move(250,680)
		self.pyx_frac_textbox.move(380,680)

		CATE.btn_mica_res = QPushButton("Mica", self)
		CATE.btn_mica_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.mica_frac_textbox, param = "mica_frac", mineral = "Mica"))
		if CATE.solid_phase_method == 1:
			CATE.btn_mica_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_mica_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_mica_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.mica_frac_textbox = QLineEdit(str(0.0), self)
		self.mica_frac_textbox.setEnabled(False)
		self.mica_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_mica_res.move(250,715)
		self.mica_frac_textbox.move(380,715)

		CATE.btn_clay_res = QPushButton("Clay", self)
		CATE.btn_clay_res.clicked.connect(lambda: self.get_mineral_value(textbox_obj=self.clay_frac_textbox, param = "clay_frac", mineral = "Clay"))
		if CATE.solid_phase_method == 1:
			CATE.btn_clay_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 0:
			CATE.btn_clay_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		elif CATE.solid_phase_method == 2:
			CATE.btn_clay_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
		self.clay_frac_textbox = QLineEdit(str(0.0), self)
		self.clay_frac_textbox.setEnabled(False)
		self.clay_frac_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		CATE.btn_clay_res.move(250,750)
		self.clay_frac_textbox.move(380,750)
		
		total_label_2 = QLabel(self)
		total_label_2.setText('Total:')
		total_label_2.setStyleSheet("QLabel {font:bold}; min-width: 100em ; fontsize: 10pt;color: red")
		total_label_2.move(250,785)
		
		self.total_min_textbox = QLineEdit(str(0.0), self)
		self.total_min_textbox.setEnabled(False)
		self.total_min_textbox.setStyleSheet("QlineEdit {min-width: 4em}")
		self.total_min_textbox.move(380,785)

		self.act_comp_btn = QPushButton('Plot Composition',self)
		self.act_comp_btn.move(10,820)
		self.act_comp_btn.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #93db88}")
		self.act_comp_btn.clicked.connect(self.plot_composition_button)

		self.show()

	def get_fluid_melt_content(self):

		text, ok = QInputDialog.getText(self, 'Melt Content Dialogue', 'Enter the value in (%):')
		if ok:
			try:
				float(text)
				if (float(text) <= 100.0) and (float(text) > 0.0):
					self.melt_content_textbox.setText(str(text))
					self.melt_fluid_frac = np.array([float(text) / 1e2])
				else:
					QMessageBox.about(self,"Warning!","Enter a value between 0 and 100")
			except ValueError:
				QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		
	def get_salinity(self):

		if CATE.fluid_or_melt_method == 0:
			text, ok = QInputDialog.getText(self, 'Salinity Content Dialogue', 'Enter the value in (%):')
			if ok:
				try:
					float(text)
					self.salinity_textbox.setText(str(text))
					self.salinity_fluid = np.array([float(text)])
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","Only fluids can have salinity. Now, the fluid phase is selected to be melt.")
		
	def get_co2_melt(self):

		if CATE.fluid_or_melt_method == 1:
			text, ok = QInputDialog.getText(self, 'CO2 Melt Dialogue', 'Enter the value in (ppm):')
			if ok:
				try:
					float(text)
					self.co2_melt_textbox.setText(str(text))
					self.co2_melt = np.array([float(text)])
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","Only melts can have co2. Now, the phase is selected to be fluid.")
		
	def get_h2o_melt(self):

		if CATE.fluid_or_melt_method == 1:
			text, ok = QInputDialog.getText(self, 'H2O Melt Dialogue', 'Enter the value in (ppm):')
			if ok:
				try:
					float(text)
					self.h2o_melt_textbox.setText(str(text))
					self.h2o_melt = np.array([float(text)])
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","Only melts can have strcutrally bounded h2o. Now, the phase is selected to be fluid.")
		
	def get_nao_melt(self):

		if CATE.fluid_or_melt_method == 1:
			text, ok = QInputDialog.getText(self, 'NaO Melt Dialogue', 'Enter the value in (%wt):')
			if ok:
				try:
					float(text)
					self.nao_melt_textbox.setText(str(text))
					self.nao_melt = np.array([float(text)])
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","Only melts can have NaO in this software. Now, the phase is selected to be fluid.")

	def get_k2o_melt(self):

		if CATE.fluid_or_melt_method == 1:
			text, ok = QInputDialog.getText(self, 'K2O Melt Dialogue', 'Enter the value in (wt%):')
			if ok:
				try:
					float(text)
					self.k2o_melt_textbox.setText(str(text))
					self.k2o_melt = np.array([float(text)])
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","Only melts can have K2O in this software. Now, the phase is selected to be fluid.")

	def get_bckgr_res(self):

		if CATE.solid_phase_method == 0:
			text, ok = QInputDialog.getText(self, 'Background Resistivity Dialogue', 'Enter the value in (ohm m):')
			if ok:
				try:
					float(text)
					self.bckgr_res_textbox.setText(str(text))
					self.bckgr_res = np.array([float(text)])
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","You selected to use experimental conductivity measurements to build the solid phases. Choose the other option ot use this method.")
	
	def get_rock_value(self, textbox_obj,param,rock):

		if CATE.solid_phase_method == 1:
			text, ok = QInputDialog.getText(self, rock + 'volume dialogue', 'Enter the value in (%)')
			if ok:
				try:
					float(text)
					if (float(text) <= 100.0) and (float(text) >= 0.0):

						textbox_obj.setText(str(text))
						setattr(self, param, np.array([float(text) /1e2]))
						self.total_rock_textbox.setText(str(self.granite_frac[0]*1e2 + self.granulite_frac[0]*1e2 +\
							self.sandstone_frac[0]*1e2 + self.gneiss_frac[0]*1e2 + self.amphibolite_frac[0]*1e2))

					else:
						QMessageBox.about(self,"Warning!","Enter a value between 0 and 100")
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","You selected to use the background resistivity mode. Choose the other option ot use experimental conductivity measurements to build a mixing model..")
	
	def get_mineral_value(self, textbox_obj, param, mineral):

		if CATE.solid_phase_method == 2:
			text, ok = QInputDialog.getText(self, mineral + 'volume dialogue', 'Enter the value in (%)')
			if ok:
				try:
					float(text)
					if (float(text) <= 100.0) and (float(text) >= 0.0):

						textbox_obj.setText(str(text))
						setattr(self, param, np.array([float(text) /1e2]))
						self.total_min_textbox.setText(str(self.quartz_frac[0]*1e2 + self.plag_frac[0]*1e2 + self.kfelds_frac[0]*1e2 +\
						self.amp_frac[0]*1e2 + self.pyx_frac[0]*1e2 + self.mica_frac[0]*1e2 + self.clay_frac[0]*1e2))

					else:
						QMessageBox.about(self,"Warning!","Enter a value between 0 and 100")
				except ValueError:
					QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
		else:
			QMessageBox.about(self,"Warning!","You selected to use the background resistivity or rock conductivity mode. Choose the other option ot use experimental conductivity measurements to build a mixing model..")
	
	def fluid_phase_popup(self):

		if self.fluid_melt_pop is None:
			self.fluid_melt_pop = FLUID_MELT_POP()
			self.fluid_melt_pop.setGeometry(QtCore.QRect(100, 500, 100, 100))
		self.fluid_melt_pop.show()

	def solid_phase_popup(self):

		if self.solid_phase_pop is None:
			self.solid_phase_pop = SOLID_PHASE_POP()
			self.solid_phase_pop.setGeometry(QtCore.QRect(100, 500, 400, 100))
		self.solid_phase_pop.show()


	def read_csv(self,filename,delim):

		#Simple function for reading csv files and give out filtered output for given delimiter (delim)

		file_obj = open(filename,'rt',encoding = "utf8") #Creating file object
		file_csv = csv.reader(file_obj,delimiter = delim) #Reading the file object with csv module, delimiter assigned to ','
		data = [] #Creating empty array to append data

		#Appending data from csb object
		for row in file_csv:
			data.append(row)

		#Filtering data for None elements read.
		for j in range(0,len(data)):
			data[j] = list(filter(None,data[j]))
		data = list(filter(None,data))

		return data

	def read_cond_models(self):

		#A function that reads conductivity model files and get the data.

		self.fluid_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'fluids.csv'),delim = ',') 
		self.melt_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'melt.csv'),delim = ',')

		#reading rocks
		self.granite_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'rocks', 'granite.csv'),delim = ',')
		self.granulite_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'rocks', 'granulite.csv'),delim = ',')
		self.sandstone_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'rocks', 'sandstone.csv'),delim = ',')
		self.gneiss_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'rocks', 'gneiss.csv'),delim = ',')
		self.amphibolite_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'rocks', 'amphibolite.csv'),delim = ',')

		#reading minerals
		self.quartz_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'quartz.csv'),delim = ',')
		self.plag_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'plag.csv'),delim = ',')
		self.amp_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'amp.csv'),delim = ',')
		self.kfelds_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'kfelds.csv'),delim = ',')
		self.pyx_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'pyx.csv'),delim = ',')
		self.mica_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'mica.csv'),delim = ',')
		self.clay_cond_data = self.read_csv(os.path.join(self.core_path, 'cond_models' , 'minerals', 'clay.csv'),delim = ',')
		

		self.cond_data_array = [self.fluid_cond_data, self.melt_cond_data, self.granite_cond_data, self.granulite_cond_data,
			  self.sandstone_cond_data, self.gneiss_cond_data, self.amphibolite_cond_data, self.quartz_cond_data, self.plag_cond_data,
			  self.amp_cond_data, self.kfelds_cond_data, self.pyx_cond_data, self.mica_cond_data, self.clay_cond_data]

		len_fluid = len(self.fluid_cond_data) - 1 
		len_melt = len(self.melt_cond_data) - 1

		self.fluid_num = 2

		len_granite = len(self.granite_cond_data) - 1
		len_granulite = len(self.granulite_cond_data) - 1
		len_sandstone = len(self.sandstone_cond_data) - 1
		len_gneiss = len(self.gneiss_cond_data) - 1
		len_amphibolite = len(self.amphibolite_cond_data) - 1
		
		self.rock_num = 5

		len_quartz = len(self.quartz_cond_data) - 1
		len_plag = len(self.plag_cond_data) - 1
		len_amp = len(self.amp_cond_data) - 1
		len_kfelds = len(self.kfelds_cond_data) - 1
		len_pyx = len(self.pyx_cond_data) - 1
		len_mica = len(self.mica_cond_data) - 1
		len_clay = len(self.clay_cond_data) - 1

		self.mineral_num = 7

		#Creating empty arrays for appending new data.
		CATE.name = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		CATE.type = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		CATE.t_min = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		CATE.t_max = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.p_min = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.p_max = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.w_calib = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.mg_cond = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.sigma_pol = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.sigma_pol_err = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.h_pol = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.h_pol_err = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.sigma_p = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.sigma_p_err = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.h_p = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.h_p_err = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.r = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.r_err = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.alpha_p = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.alpha_p_err = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.wtype = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]
		self.dens_mat = [[None] * len_fluid, [None] * len_melt, [None] * len_granite, [None] * len_granulite, [None] * len_sandstone, [None] * len_gneiss,
		   [None] * len_amphibolite, [None] * len_quartz, [None] * len_plag, [None] * len_amp, [None] * len_kfelds, [None] * len_pyx, [None] * len_mica, [None] * len_clay]

		#Filling up the arrays.
		for i in range(0,len(CATE.type)):
			count = 1
			for j in range(0,len(CATE.type[i])):

				CATE.name[i][count-1] = self.cond_data_array[i][count][0]
				CATE.type[i][count-1] = self.cond_data_array[i][count][1]
				CATE.t_min[i][count-1] = float(self.cond_data_array[i][count][2])
				CATE.t_max[i][count-1] = float(self.cond_data_array[i][count][3])
				self.p_min[i][count-1] = float(self.cond_data_array[i][count][4])
				self.p_max[i][count-1] = float(self.cond_data_array[i][count][5])
				self.w_calib[i][count-1] = int(self.cond_data_array[i][count][6])
				self.mg_cond[i][count-1] = float(self.cond_data_array[i][count][7])
				self.sigma_pol[i][count-1] = float(self.cond_data_array[i][count][8])
				self.sigma_pol_err[i][count-1] = float(self.cond_data_array[i][count][9])
				self.h_pol[i][count-1] = float(self.cond_data_array[i][count][10])
				self.h_pol_err[i][count-1] = float(self.cond_data_array[i][count][11])
				self.sigma_p[i][count-1] = float(self.cond_data_array[i][count][12])
				self.sigma_p_err[i][count-1] = float(self.cond_data_array[i][count][13])
				self.h_p[i][count-1] = float(self.cond_data_array[i][count][14])
				self.h_p_err[i][count-1] = float(self.cond_data_array[i][count][15])
				self.r[i][count-1] = float(self.cond_data_array[i][count][16])
				self.r_err[i][count-1] = float(self.cond_data_array[i][count][17])
				self.alpha_p[i][count-1] = float(self.cond_data_array[i][count][18])
				self.alpha_p_err[i][count-1] = float(self.cond_data_array[i][count][19])
				self.wtype[i][count-1] = int(self.cond_data_array[i][count][20])
				self.dens_mat[i][count-1] = float(self.cond_data_array[i][count][21])
			
				count += 1

	def check_composition(self):

		continue_adjusting = True

		if CATE.solid_phase_method == 0:

			pass

		elif CATE.solid_phase_method == 1:

			tot = self.granite_frac + self.granulite_frac + self.sandstone_frac +\
			self.gneiss_frac + self.amphibolite_frac

			if tot != 1.0:
				QMessageBox.about(self, "Warning!", "The total number of does not add up to 100%. Currently it is:  " + str(tot*1e2))
				continue_adjusting = False
		elif CATE.solid_phase_method == 2:

			tot = self.quartz_frac + self.plag_frac + self.amp_frac + self.kfelds_frac +\
			self.pyx_frac + self.mica_frac + self.clay_frac

			if tot != 1.0:
				QMessageBox.about(self, "Warning!", "The total number of does not add up to 100%. Currently it is:  " + str(tot*1e2))
				continue_adjusting = False

		return continue_adjusting
	
	def calculate_arrhenian_single(self, T, sigma, E, r=0, water=1):

		cond = sigma * (water**r) * np.exp((-E) / (self.R * T))

		return cond
	
	def calculate_fluids_conductivity(self, method, sol_idx = None):

		if method == 'array':
			idx_node = None
		elif method == 'index':
			idx_node = sol_idx

		if CATE.type[0][CATE.fluid_cond_selection] == '0':

			self.fluid_cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node], P = self.p[idx_node],
								   sigma = self.sigma_pol[0][CATE.fluid_cond_selection],
								   E = self.h_pol[0][CATE.fluid_cond_selection])
			
		elif CATE.type[0][CATE.fluid_cond_selection] == '1':

			self.fluid_cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node],
								   sigma = self.sigma_pol[0][CATE.fluid_cond_selection],
								   E = self.h_pol[0][CATE.fluid_cond_selection]) + self.calculate_arrhenian_single(T = self.T[idx_node],
								   sigma = self.sigma_p[0][CATE.fluid_cond_selection],
								   E = self.h_p[0][CATE.fluid_cond_selection])
			
		elif CATE.type[0][CATE.fluid_cond_selection] == '3':

			if ('*' in CATE.name[0][CATE.fluid_cond_selection]) == True:

				fluids_odd_function = CATE.name[0][CATE.fluid_cond_selection].replace('*','')

			else:

				fluids_odd_function = CATE.name[0][CATE.fluid_cond_selection]

			cond_fluids_max, cond_fluids_min, cond_fluids = eval(fluids_odd_function + '(T = self.T[idx_node], P = self.p[idx_node], NaCL = self.nacl[idx_node], method = method)')

		self.fluids_cond[idx_node] = cond_fluids
		if method == 'array':
			self.fluids_cond_max[idx_node] = cond_fluids_max
			self.fluids_cond_min[idx_node] = cond_fluids_min
		else:
			self.fluids_cond_max[idx_node] = self.fluids_cond[idx_node]
			self.fluids_cond_min[idx_node] = self.fluids_cond[idx_node]

	def calculate_melt_conductivity(self, method, sol_idx = None):

		if method == 'array':
			idx_node = None
		elif method == 'index':
			idx_node = sol_idx

		if CATE.type[1][CATE.melt_cond_selection] == '0':

			self.melt_cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node], P = self.p[idx_node],
								   sigma = self.sigma_pol[1][CATE.melt_cond_selection],
								   E = self.h_pol[1][CATE.melt_cond_selection])
			
		elif CATE.type[1][CATE.melt_cond_selection] == '1':

			self.melt_cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node],
								   sigma = self.sigma_pol[1][CATE.melt_cond_selection],
								   E = self.h_pol[1][CATE.melt_cond_selection]) + self.calculate_arrhenian_single(T = self.T[idx_node],
								   sigma = self.sigma_p[1][CATE.melt_cond_selection],
								   E = self.h_p[1][CATE.melt_cond_selection])
			
		elif CATE.type[1][CATE.melt_cond_selection] == '3':

			if ('*' in CATE.name[1][CATE.melt_cond_selection]) == True:

				melt_odd_function = CATE.name[1][CATE.melt_cond_selection].replace('*','')

			else:

				melt_odd_function = CATE.name[1][CATE.melt_cond_selection]

			cond_melt = eval(melt_odd_function + '(T = self.T[idx_node], P = self.p[idx_node], NaCL = self.nacl[idx_node], method = method)')

		self.melt_cond[idx_node] = cond_melt

	def calculate_rock_conductivity(self, method, rock_idx = None, sol_idx = None):

		if method == 'array':
			idx_node = None
		elif method == 'index':
			idx_node = sol_idx

		if CATE.type[rock_idx][self.rock_cond_selections[rock_idx]] == '0':

			cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node], P = self.p[idx_node],
								   sigma = self.sigma_pol[rock_idx][self.rock_cond_selections[rock_idx]],
								   E = self.h_pol[rock_idx][self.rock_cond_selections[rock_idx]])
			
		elif CATE.type[rock_idx][self.rock_cond_selections[rock_idx]] == '1':

			cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node], P = self.p[idx_node],
								   sigma = self.sigma_pol[rock_idx][self.rock_cond_selections[rock_idx]],
								   E = self.h_pol[rock_idx][self.rock_cond_selections[rock_idx]]) + self.calculate_arrhenian_single(T = self.T[idx_node],
								   sigma = self.sigma_p[rock_idx][self.rock_cond_selections[rock_idx]],
								   E = self.h_p[rock_idx][self.rock_cond_selections[rock_idx]])
			
		elif CATE.type[rock_idx][self.rock_cond_selections[rock_idx]] == '3':

			if ('*' in CATE.name[rock_idx][self.rock_cond_selections[rock_idx]]) == True:

				odd_function = CATE.name[rock_idx][self.rock_cond_selections[rock_idx]].replace('*','')

			else:

				odd_function = CATE.name[rock_idx][self.rock_cond_selections[rock_idx]]

			cond = eval(odd_function + '(T = self.T[idx_node], P = self.p[idx_node], NaCL = self.nacl[idx_node], method = method)') #carla

		return cond
	
	def calculate_mineral_conductivity(self, method, min_idx = None, sol_idx = None):

		if method == 'array':
			idx_node = None
		elif method == 'index':
			idx_node = sol_idx

		if CATE.type[min_idx][self.minerals_cond_selections[min_idx]] == '0':

			cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node], P = self.p[idx_node],
								   sigma = self.sigma_pol[min_idx][self.minerals_cond_selections[min_idx]],
								   E = self.h_pol[min_idx][self.minerals_cond_selections[min_idx]])
			
		elif CATE.type[min_idx][self.minerals_cond_selections[min_idx]] == '1':

			cond[idx_node] = self.calculate_arrhenian_single(T = self.T[idx_node], P = self.p[idx_node],
								   sigma = self.sigma_pol[min_idx][self.minerals_cond_selections[min_idx]],
								   E = self.h_pol[min_idx][self.minerals_cond_selections[min_idx]]) + self.calculate_arrhenian_single(T = self.T[idx_node],
								   sigma = self.sigma_p[min_idx][self.minerals_cond_selections[min_idx]],
								   E = self.h_p[min_idx][self.minerals_cond_selections[min_idx]])
			
		elif CATE.type[min_idx][self.minerals_cond_selections[min_idx]] == '3':

			if ('*' in CATE.name[min_idx][self.minerals_cond_selections[min_idx]]) == True:

				odd_function = CATE.name[min_idx][self.minerals_cond_selections[min_idx]].replace('*','')

			else:

				odd_function = CATE.name[min_idx][self.minerals_cond_selections[min_idx]]

			cond = eval(odd_function + '(T = self.T[idx_node], P = self.p[idx_node], NaCL = self.nacl[idx_node], method = method)') #carla

		return cond
	
	def plot_composition(self, method = None):

		if method == 'draw':
			
			self.ax0 = plt.subplot2grid((16,16),(0,0), rowspan = 4,colspan = 3, fig = self.fig)
			self.ax1 = plt.subplot2grid((16,16),(0,6), rowspan = 4,colspan = 3, fig = self.fig)
			
		elif method == 'save':
		
			self.figure_comp_save = plt.figure(figsize = (2,7))
			fontsize_labels = 10
			self.ax0 = plt.subplot(111)
			
		self.label_general_rocks = ['Granite', 'Granulite', 'Sandstone', 'Gneiss', 'Amphibolite']
		self.color_general_rocks = ['#e016c2',"#52081b","#f0cf6e","#cbe0c3","#41453f"]
		labels = []
		label_colors = []
		
		self.label_general_mins = ['Quartz', 'Plagioclase', 'Amphibole', 'K-Feldspar', 'Pyroxenes', 'Mica', 'Clay']
		self.color_general_mins = ["#f7f7d7","#fad9a0", "#bfbab2", "#fa5f93", "#3747b0", "#36cf45", "#574018"]
				
		if CATE.solid_phase_method == 0:
			self.solid_phase_array = np.array([100])
			labels = ['Rock\n Assemblage']
			label_colors = ['#70653f']
		elif CATE.solid_phase_method == 1:
			
			self.solid_phase_array = []
			solid_phase_array = [self.granite_frac, self.granulite_frac,self.sandstone_frac,
			self.gneiss_frac,self.amphibolite_frac]
			
			for i in range(0,len(solid_phase_array)):
				if solid_phase_array[i][0] != 0.0:
					self.solid_phase_array.append(solid_phase_array[i][0]*1e2)
					labels.append(self.label_general_rocks[i])
					label_colors.append(self.color_general_rocks[i])
					
		elif CATE.solid_phase_method == 2:
		
			self.solid_phase_array = []
			solid_phase_array = [self.quartz_frac, self.plag_frac, self.kfelds_frac, self.amp_frac, self.pyx_frac,
			self.mica_frac,self.clay_frac]
			
			for i in range(0,len(solid_phase_array)):
				if solid_phase_array[i][0] != 0.0:
					
					self.solid_phase_array.append(solid_phase_array[i][0]*1e2)
					labels.append(self.label_general_mins[i])
					label_colors.append(self.color_general_mins[i])
					
					
		solid = (1 - self.melt_fluid_frac[0]) * 1e2
		liquid = self.melt_fluid_frac[0] * 1e2
		
		sol_liq_array = []
		labels_fs = []
		color_fs = []
		
		if solid != 0:
			sol_liq_array.append(solid)
			labels_fs.append('Solid')
			color_fs.append('#70653f')
		
		if liquid != 0:
		
			sol_liq_array.append(liquid)
			
			if CATE.fluid_or_melt_method == 1:
				label_f = 'Melt'
				color_f = '#912c10'
			else:
				label_f = 'Fluid'
				color_f = '#24abad'
		
			labels_fs.append(label_f)
			color_fs.append(color_f)
		
		self.ax0.pie(self.solid_phase_array, labels = labels, colors = label_colors,radius = 2,autopct='%1.1f%%')
		self.ax1.pie(sol_liq_array, labels = labels_fs, colors = color_fs,radius = 2, autopct='%1.1f%%')
		
		if method == 'draw':
		
			self.canvas.draw()


	def info_main(self):
		QMessageBox.about(self, "INFO GENERAL", "TBW.")

	def plot_composition_button(self):
	
		bool_comp = self.check_composition()

		if bool_comp == True:

			self.plot_composition(method = 'draw')
			self.act_comp_btn.setStyleSheet("QPushButton {min-width: 10em; font: bold; font-size: 9pt;background-color: #679c5f}")

	def conductivity_popup(self):

		if self.cond_pop is None:
			self.cond_pop = COND_POP()
			self.cond_pop.setGeometry(QtCore.QRect(1000, 700, 100, 100))
		self.cond_pop.show()

	def phase_mixing_popup(self):

		if self.phs_mix_popup is None:
			self.phs_mix_popup = PHS_MIX_POP()
			self.phs_mix_popup.setGeometry(QtCore.QRect(100, 100, 1000, 200))
		self.phs_mix_popup.show()
		
	def phase_intercon_popup(self):
	
		if self.phs_intercon_popup is None:
			self.phs_intercon_popup = PHS_INTER_POP()
			self.phs_intercon_popup.setGeometry(QtCore.QRect(100, 100, 300, 200))
		self.phs_intercon_popup.show()

class FLUID_MELT_POP(QWidget):

	def __init__(self):

		QWidget.__init__(self)

		fluid_melt_layout = QVBoxLayout(self)

		fluid_melt_label = QLabel(self)
		fluid_melt_label.setText('Select the fluid phase')
		fluid_melt_label.setStyleSheet("QLabel {font:bold};fontsize: 10pt;color: red")


		fluid_melt_btg = QButtonGroup(self)

		self.btn_fom_1 = QRadioButton("Fluid")
		self.btn_fom_1.toggled.connect(lambda:self.btnstate_fluidormelt(self.btn_fom_1))
		self.btn_fom_2 = QRadioButton("Melt")
		self.btn_fom_2.toggled.connect(lambda:self.btnstate_fluidormelt(self.btn_fom_2))

		if CATE.fluid_or_melt_method == 0:
			self.btn_fom_1.setChecked(True)
		elif CATE.fluid_or_melt_method == 1:
			self.btn_fom_2.setChecked(True)

		fluid_melt_btg.addButton(self.btn_fom_1)
		fluid_melt_btg.addButton(self.btn_fom_2)

		fluid_melt_layout.addWidget(fluid_melt_label)
		fluid_melt_layout.addWidget(self.btn_fom_1)
		fluid_melt_layout.addWidget(self.btn_fom_2)

	def btnstate_fluidormelt(self,b):

		if b.text() == "Fluid":
			if b.isChecked() == True:
				CATE.fluid_or_melt_method = 0
				CATE.btn_salinity_fluid.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_co2_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_h2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_nao_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_k2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		if b.text() == "Melt":
			if b.isChecked() == True:
				CATE.fluid_or_melt_method = 1
				CATE.btn_salinity_fluid.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_co2_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_h2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_nao_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_k2o_melt.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")


class SOLID_PHASE_POP(QWidget):

	def __init__(self):

		QWidget.__init__(self)

		layout = QVBoxLayout(self)

		main_label = QLabel(self)
		main_label.setText('Select the solid phase option.')
		main_label.setStyleSheet("QLabel {font:bold};min-width: 10em; fontsize: 10pt;color: red")

		solid_phase_btg = QButtonGroup(self)

		self.btn_sphase_1 = QRadioButton("Background Resistivity Entry")
		self.btn_sphase_1.toggled.connect(lambda:self.btnstate_solid_phase_setup(self.btn_sphase_1))
		self.btn_sphase_2 = QRadioButton("Experimental Conductivity Measurements of Rocks")
		self.btn_sphase_2.toggled.connect(lambda:self.btnstate_solid_phase_setup(self.btn_sphase_2))
		self.btn_sphase_3 = QRadioButton("Experimental Conductivity Measurements of Minerals")
		self.btn_sphase_3.toggled.connect(lambda:self.btnstate_solid_phase_setup(self.btn_sphase_3))

		if CATE.solid_phase_method == 0:
			self.btn_sphase_1.setChecked(True)
		elif CATE.solid_phase_method == 1:
			self.btn_sphase_2.setChecked(True)
		elif CATE.solid_phase_method == 2:
			self.btn_sphase_3.setChecked(True)

		solid_phase_btg.addButton(self.btn_sphase_1)
		solid_phase_btg.addButton(self.btn_sphase_2)
		solid_phase_btg.addButton(self.btn_sphase_3)

		layout.addWidget(main_label)
		layout.addWidget(self.btn_sphase_1)
		layout.addWidget(self.btn_sphase_2)
		layout.addWidget(self.btn_sphase_3)

	def btnstate_solid_phase_setup(self,b):

		if b.text() == "Background Resistivity Entry":
			if b.isChecked() == True:
				CATE.solid_phase_method = 0
				CATE.btn_bckgr_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_granite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_granulite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_sandstone_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_amphibolite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_quartz_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_plag_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_amp_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_kfelds_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_pyx_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_mica_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_clay_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		if b.text() == "Experimental Conductivity Measurements of Rocks":
			if b.isChecked() == True:
				CATE.solid_phase_method = 1
				CATE.btn_bckgr_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_granite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_granulite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_sandstone_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_amphibolite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_quartz_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_plag_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_amp_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_kfelds_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_pyx_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_mica_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_clay_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
		if b.text() == "Experimental Conductivity Measurements of Minerals":
			if b.isChecked() == True:
				CATE.solid_phase_method = 2
				CATE.btn_bckgr_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_granite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_granulite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_sandstone_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_gneiss_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_amphibolite_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #6b786e}")
				CATE.btn_quartz_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_plag_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_amp_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_kfelds_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_pyx_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_mica_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")
				CATE.btn_clay_res.setStyleSheet("QPushButton {min-width: 8em; font: bold; font-size: 9pt;background-color: #c8cccc}")

class PHS_MIX_POP(QWidget):

	def __init__(self):

		QWidget.__init__(self)

		layout = QGridLayout(self)

		bg1 = QButtonGroup(self)
		
		label_solid_mix = QLabel(self)
		label_solid_mix.setText('--------Solid-State Mixing--------')
		label_solid_mix.setStyleSheet("QLabel {font:bold};min-width: 10em; fontsize: 10pt;color: red")
		layout.addWidget(label_solid_mix,0,0)
		
		self.btn_mix_1 = QRadioButton("Generalized Archie's Law (Glover, 2010)")
		self.btn_mix_1.toggled.connect(lambda:self.btnstate_phsmix(self.btn_mix_1))
		self.btn_mix_2 = QRadioButton("Hashin-Shtrikman Lower Bound (Berryman, 1995)")
		self.btn_mix_2.toggled.connect(lambda:self.btnstate_phsmix(self.btn_mix_2))
		self.btn_mix_3 = QRadioButton("Hashin-Shtrikman Upper Bound (Berryman, 1995)")
		self.btn_mix_3.toggled.connect(lambda:self.btnstate_phsmix(self.btn_mix_3))
		self.btn_mix_4 = QRadioButton("Parallel Model (Guegen and Palciauskas, 1994)")
		self.btn_mix_4.toggled.connect(lambda:self.btnstate_phsmix(self.btn_mix_4))
		self.btn_mix_5 = QRadioButton("Perpendicular Model (Guegen and Palciauskas, 1994)")
		self.btn_mix_5.toggled.connect(lambda:self.btnstate_phsmix(self.btn_mix_5))
		self.btn_mix_6 = QRadioButton("Random Model (Guegen and Palciauskas, 1994)")
		self.btn_mix_6.toggled.connect(lambda:self.btnstate_phsmix(self.btn_mix_6))
		
		if CATE.phs_mix_method == 0:
			self.btn_mix_1.setChecked(True)
		elif CATE.phs_mix_method == 1:
			self.btn_mix_2.setChecked(True)
		elif CATE.phs_mix_method == 2:
			self.btn_mix_3.setChecked(True)
		elif CATE.phs_mix_method == 3:
			self.btn_mix_4.setChecked(True)
		elif CATE.phs_mix_method == 4:
			self.btn_mix_5.setChecked(True)
		elif CATE.phs_mix_method == 5:
			self.btn_mix_6.setChecked(True)
			
		bg1.addButton(self.btn_mix_1)
		bg1.addButton(self.btn_mix_2)
		bg1.addButton(self.btn_mix_3)
		bg1.addButton(self.btn_mix_4)
		bg1.addButton(self.btn_mix_5)
		bg1.addButton(self.btn_mix_6)
		
		layout.addWidget(self.btn_mix_1,1,0)
		layout.addWidget(self.btn_mix_2,2,0)
		layout.addWidget(self.btn_mix_3,3,0)
		layout.addWidget(self.btn_mix_4,4,0)
		layout.addWidget(self.btn_mix_5,5,0)
		layout.addWidget(self.btn_mix_6,6,0)
		
		label_melt_mix = QLabel(self)
		label_melt_mix.setText('--------Melt/Fluid-Solid Mixing--------')
		label_melt_mix.setStyleSheet("QLabel {font:bold};min-width: 10em; fontsize: 10pt;color: red")
		layout.addWidget(label_melt_mix,0,1)

		self.btn_mix_melt_1 = QRadioButton("Modified Archie's Law (Glover et al., 2000)")
		self.btn_mix_melt_1.toggled.connect(lambda:self.btnstate_phsmix_melt(self.btn_mix_melt_1))
		self.btn_mix_melt_2 = QRadioButton("Tubes Model (ten Grotenhuis et al., 2005)")
		self.btn_mix_melt_2.toggled.connect(lambda:self.btnstate_phsmix_melt(self.btn_mix_melt_2))
		self.btn_mix_melt_3 = QRadioButton("Spheres Model (ten Grotenhuis et al., 2005)")
		self.btn_mix_melt_3.toggled.connect(lambda:self.btnstate_phsmix_melt(self.btn_mix_melt_3))
		self.btn_mix_melt_4 = QRadioButton("Modified Brick-layer Model (Schilling et al., 1997)")
		self.btn_mix_melt_4.toggled.connect(lambda:self.btnstate_phsmix_melt(self.btn_mix_melt_4))
		self.btn_mix_melt_5 = QRadioButton("Hashin-Shtrikman Upper-Bound (Glover et al., 2000)")
		self.btn_mix_melt_5.toggled.connect(lambda:self.btnstate_phsmix_melt(self.btn_mix_melt_5))
		self.btn_mix_melt_6 = QRadioButton("Hashin-Shtrikman Lower-Bound (Glover et al., 2000)")
		self.btn_mix_melt_6.toggled.connect(lambda:self.btnstate_phsmix_melt(self.btn_mix_melt_6))

		bg2 = QButtonGroup(self)

		bg2.addButton(self.btn_mix_melt_1)
		bg2.addButton(self.btn_mix_melt_2)
		bg2.addButton(self.btn_mix_melt_3)
		bg2.addButton(self.btn_mix_melt_4)
		bg2.addButton(self.btn_mix_melt_5)
		bg2.addButton(self.btn_mix_melt_6)

		layout.addWidget(self.btn_mix_melt_1,1,1)
		layout.addWidget(self.btn_mix_melt_2,2,1)
		layout.addWidget(self.btn_mix_melt_3,3,1)
		layout.addWidget(self.btn_mix_melt_4,4,1)
		layout.addWidget(self.btn_mix_melt_5,5,1)
		layout.addWidget(self.btn_mix_melt_6,6,1)

		if CATE.phs_melt_mix_method == 0:
			self.btn_mix_melt_1.setChecked(True)
		elif CATE.phs_melt_mix_method == 1:
			self.btn_mix_melt_2.setChecked(True)
		elif CATE.phs_melt_mix_method == 2:
			self.btn_mix_melt_3.setChecked(True)
		elif CATE.phs_melt_mix_method == 3:
			self.btn_mix_melt_4.setChecked(True)
		elif CATE.phs_melt_mix_method == 4:
			self.btn_mix_melt_5.setChecked(True)
		elif CATE.phs_melt_mix_method == 5:
			self.btn_mix_melt_6.setChecked(True)


	def btnstate_phsmix(self,b):

		if b.text() == "Generalized Archie's Law (Glover, 2010)":
			if b.isChecked() == True:
				CATE.phs_mix_method = 0
		if b.text() == "Hashin-Shtrikman Lower Bound (Berryman, 1995)":
			if b.isChecked() == True:
				CATE.phs_mix_method = 1
		if b.text() == "Hashin-Shtrikman Upper Bound (Berryman, 1995)":
			if b.isChecked() == True:
				CATE.phs_mix_method = 2
		if b.text() == "Parallel Model (Guegen and Palciauskas, 1994)":
			if b.isChecked() == True:
				CATE.phs_mix_method = 3
		if b.text() == "Perpendicular Model (Guegen and Palciauskas, 1994)":
			if b.isChecked() == True:
				CATE.phs_mix_method = 4
		if b.text() == "Random Model (Guegen and Palciauskas, 1994)":
			if b.isChecked() == True:
				CATE.phs_mix_method = 5
				
				
	def btnstate_phsmix_melt(self, b2):

		if b2.text() == "Modified Archie's Law (Glover et al., 2000)":
			if b2.isChecked() == True:
				CATE.phs_melt_mix_method = 0
				CATE.phs_melt_mix_type = 0
		elif b2.text() == "Tubes Model (ten Grotenhuis et al., 2005)":
			if b2.isChecked() == True:
				CATE.phs_melt_mix_method = 1
				CATE.phs_melt_mix_type = 1
		elif b2.text() == "Spheres Model (ten Grotenhuis et al., 2005)":
			if b2.isChecked() == True:
				CATE.phs_melt_mix_method = 2
				CATE.phs_melt_mix_type = 1
		elif b2.text() == "Modified Brick-layer Model (Glover et al., 2000)":
			if b2.isChecked() == True:
				CATE.phs_melt_mix_method = 3
				CATE.phs_melt_mix_type = 1
		elif b2.text() == "Hashin-Shtrikman Upper-Bound (Glover et al., 2000)":
			if b2.isChecked() == True:
				CATE.phs_melt_mix_method = 4
				CATE.phs_melt_mix_type = 1
		elif b2.text() == "Hashin-Shtrikman Lower-Bound (Glover et al., 2000)":
			if b2.isChecked() == True:
				CATE.phs_melt_mix_method = 5
				CATE.phs_melt_mix_type = 1
				
class PHS_INTER_POP(QWidget):

	def __init__(self):
	
		QWidget.__init__(self)

		layout = QFormLayout(self)

		desc_label = QLabel(self)
		desc_label.setText('---Enter Interconnectivity (Cementation exponent) values---')
		desc_label.setStyleSheet("QLabel {font:bold};fontsize: 10pt;color: red")
		
		self.melt_fluid_m_btn = QPushButton('Melt/Fluid m')
		self.melt_fluid_m_textbox = QLineEdit(str(CATE.melt_fluid_m))
		self.melt_fluid_m_textbox.setEnabled(False)
		self.melt_fluid_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.melt_fluid_m_textbox, param = "melt_fluid_m"))


		#rocks
		rocks_label = QLabel(self)
		rocks_label.setText('---Rocks---')
		rocks_label.setStyleSheet("QLabel {font:bold};fontsize: 10pt;color: red")

		self.granite_m_btn = QPushButton('Granite m')
		self.granite_m_textbox = QLineEdit(str(CATE.granite_m))
		self.granite_m_textbox.setEnabled(False)
		self.granite_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.granite_m_textbox, param = "granite_m"))

		self.granulite_m_btn = QPushButton('Granulite m')
		self.granulite_m_textbox = QLineEdit(str(CATE.granulite_m))
		self.granulite_m_textbox.setEnabled(False)
		self.granulite_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.granulite_m_textbox, param = "granulite_m"))

		self.sandstone_m_btn = QPushButton('Sandstone m')
		self.sandstone_m_textbox = QLineEdit(str(CATE.sandstone_m))
		self.sandstone_m_textbox.setEnabled(False)
		self.sandstone_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.sandstone_m_textbox, param = "sandstone_m"))

		self.gneiss_m_btn = QPushButton('Gneiss m')
		self.gneiss_m_textbox = QLineEdit(str(CATE.gneiss_m))
		self.gneiss_m_textbox.setEnabled(False)
		self.gneiss_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.gneiss_m_textbox, param = "gneiss_m"))

		self.amphibolite_m_btn = QPushButton('Amphibolite m')
		self.amphibolite_m_textbox = QLineEdit(str(CATE.amphibolite_m))
		self.amphibolite_m_textbox.setEnabled(False)
		self.amphibolite_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.amphibolite_m_textbox, param = "amphibolite_m"))
		
		#minerals
		minerals_label = QLabel(self)
		minerals_label.setText('---Mineral---')
		minerals_label.setStyleSheet("QLabel {font:bold};fontsize: 10pt;color: red")

		self.quartz_m_btn = QPushButton('Quartz m')
		self.quartz_m_textbox = QLineEdit(str(CATE.quartz_m))
		self.quartz_m_textbox.setEnabled(False)
		self.quartz_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.quartz_m_textbox, param = "quartz_m"))

		self.plag_m_btn = QPushButton('Plagioclase m')
		self.plag_m_textbox = QLineEdit(str(CATE.plag_m))
		self.plag_m_textbox.setEnabled(False)
		self.plag_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.plag_m_textbox, param = "plag_m"))

		self.amp_m_btn = QPushButton('Amphibole m')
		self.amp_m_textbox = QLineEdit(str(CATE.amp_m))
		self.amp_m_textbox.setEnabled(False)
		self.amp_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.amp_m_textbox, param = "amp_m"))

		self.kfelds_m_btn = QPushButton('K-Feldspar m')
		self.kfelds_m_textbox = QLineEdit(str(CATE.kfelds_m))
		self.kfelds_m_textbox.setEnabled(False)
		self.kfelds_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.kfelds_m_textbox, param = "kfelds_m"))

		self.pyx_m_btn = QPushButton('Pyroxene m')
		self.pyx_m_textbox = QLineEdit(str(CATE.pyx_m))
		self.pyx_m_textbox.setEnabled(False)
		self.pyx_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.pyx_m_textbox, param = "pyx_m"))

		self.mica_m_btn = QPushButton('Mica m')
		self.mica_m_textbox = QLineEdit(str(CATE.mica_m))
		self.mica_m_textbox.setEnabled(False)
		self.mica_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.mica_m_textbox, param = "mica_m"))

		self.clay_m_btn = QPushButton('Clay m')
		self.clay_m_textbox = QLineEdit(str(CATE.clay_m))
		self.clay_m_textbox.setEnabled(False)
		self.clay_m_btn.clicked.connect(lambda: self.get_interconnectivity(textbox_obj=self.clay_m_textbox, param = "clay_m"))


		layout.addRow(desc_label)
		layout.addRow(self.melt_fluid_m_btn, self.melt_fluid_m_textbox)

		layout.addRow(rocks_label)

		layout.addRow(self.granite_m_btn, self.granite_m_textbox)
		layout.addRow(self.granulite_m_btn, self.granulite_m_textbox)
		layout.addRow(self.sandstone_m_btn, self.sandstone_m_textbox)
		layout.addRow(self.gneiss_m_btn, self.gneiss_m_textbox)
		layout.addRow(self.amphibolite_m_btn, self.amphibolite_m_textbox)

		layout.addRow(minerals_label)

		layout.addRow(self.quartz_m_btn, self.quartz_m_textbox)
		layout.addRow(self.plag_m_btn, self.plag_m_textbox)
		layout.addRow(self.amp_m_btn, self.amp_m_textbox)
		layout.addRow(self.kfelds_m_btn, self.kfelds_m_textbox)
		layout.addRow(self.pyx_m_btn, self.pyx_m_textbox)
		layout.addRow(self.mica_m_btn, self.mica_m_textbox)
		layout.addRow(self.clay_m_btn, self.clay_m_textbox)




	def get_interconnectivity(self,textbox_obj,param):

		text, ok = QInputDialog.getText(self, 'Interconnectivity dialogue', 'Enter the value (bigger than 1)')
		if ok:
			try:
				float(text)
				if (float(text) >= 1):

					textbox_obj.setText(str(text))
					setattr(CATE, param, float(text))

				else:
					QMessageBox.about(self,"Warning!","Enter a value above 1")
			except ValueError:
				QMessageBox.about(self,"Warning!","Please enter a value that can be converted to floating number.")
				
		
def main():

	app = QApplication(sys.argv)
	GUI = CATE()
	sys.exit(app.exec_())

if __name__ == '__main__':
	main()